package com.project.demo.logic.entity.product;

import com.project.demo.logic.entity.category.Category;
import com.project.demo.logic.entity.category.CategoryRepository;
import org.springframework.context.ApplicationListener;
import org.springframework.context.event.ContextRefreshedEvent;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Seeder del catalogo real de productos (519 items) tomado de la tienda
 * en linea (chupis.tiendaonline.cr): nombre, categoria, precio y descripcion.
 * Las categorias las crea CategorySeeder (Order 1); este seeder corre despues
 * (Order 2) y solo enlaza cada producto a una categoria ya existente.
 * No duplica datos si ya hay productos cargados.
 */
@Order(2)
@Component
public class ProductSeeder implements ApplicationListener<ContextRefreshedEvent> {

    private final CategoryRepository categoryRepository;
    private final ProductRepository productRepository;

    public ProductSeeder(CategoryRepository categoryRepository, ProductRepository productRepository) {
        this.categoryRepository = categoryRepository;
        this.productRepository = productRepository;
    }

    @Override
    public void onApplicationEvent(ContextRefreshedEvent event) {
        loadProducts();
    }

    private void loadProducts() {
        // Si ya hay productos cargados, no se vuelve a sembrar la tabla.
        if (productRepository.count() > 0) {
            return;
        }

        List<ProductSeedData> products = List.of(
                new ProductSeedData("SILLA RUEDAS  DE 18 PULGADAS CON DESCANSA PIES ELEVABLES  PROBASIC 175000", "Sillas de Ruedas", 175000.0, ""),
                new ProductSeedData("SILLA RUEDAS VERMEIREN D200 240000", "Sillas de Ruedas", 275000.0, ""),
                new ProductSeedData("SILLA RUEDAS  20 PULGADAS PROBASIC KADLX", "Sillas de Ruedas", 220000.0, ""),
                new ProductSeedData("SILLA RUEDAS L223NMFIMU2 16¨¨¨ 240000", "Sillas de Ruedas", 240000.0, ""),
                new ProductSeedData("SILLA RUEDAS UNIVERSAL TLP  100000", "Sillas de Ruedas", 100000.0, ""),
                new ProductSeedData("SCOOTER SERIES-A ROJO VIVE 900000", "Sillas de Ruedas", 900000.0, ""),
                new ProductSeedData("SILLA RUEDAS 18 PULGADAS V500 LIGHT", "Sillas de Ruedas", 440000.0, ""),
                new ProductSeedData("SILLA RUEDAS 16X16 PROBASIC 175000", "Sillas de Ruedas", 175000.0, ""),
                new ProductSeedData("SILLA RUEDAS PROACTIVE 18 PULGADAS  220000", "Sillas de Ruedas", 220000.0, ""),
                new ProductSeedData("SILLA DE RUEDAS PROBASICS 20X16   207700", "Sillas de Ruedas", 207700.0, ""),
                new ProductSeedData("BASTON LILA AJUSTABLE MARCA CAREX", "Movilidad y Desplazamiento", 14729.0, ""),
                new ProductSeedData("ZAPATO PRECAMINADOR IMPULSO OPERA TALLA 19 25000", "Movilidad y Desplazamiento", 25000.0, ""),
                new ProductSeedData("TAPON DE BASTON TALLA 7/8 4000 CAREX", "Movilidad y Desplazamiento", 4532.0, ""),
                new ProductSeedData("ANDADERA PROACTIVE", "Movilidad y Desplazamiento", 0.0, ""),
                new ProductSeedData("ALCANZA OBJETOS CAREX 32''", "Movilidad y Desplazamiento", 14729.0, ""),
                new ProductSeedData("TAPON BASTON 1 PUNTO NACIONAL  1700", "Movilidad y Desplazamiento", 1700.0, ""),
                new ProductSeedData("ANDADERA CON ASIENTO VIVE AZUL", "Movilidad y Desplazamiento", 180000.0, ""),
                new ProductSeedData("BASTON 4 PUNTOS BASE PEQUEÑA MEDLINE", "Movilidad y Desplazamiento", 17000.0, "MDS86222CHR"),
                new ProductSeedData("ANDADERA CON ASIENTO NEGRA  75000", "Movilidad y Desplazamiento", 75000.0, ""),
                new ProductSeedData("ANDADERA 4 PUNTOS NIÑO CON RODINES ANTERIORES 45000", "Movilidad y Desplazamiento", 45000.0, ""),
                new ProductSeedData("TAPON DE BASTON TALLA 3/4 4000 CAREX", "Movilidad y Desplazamiento", 4532.0, ""),
                new ProductSeedData("ZAPATO PRECAMINADOR IMPULSO OPERA TALLA 21  25000", "Movilidad y Desplazamiento", 25000.0, ""),
                new ProductSeedData("BASTON AJUSTABLE Carex", "Movilidad y Desplazamiento", 17000.0, ""),
                new ProductSeedData("TAPON DE 4 PUNTOS PARA BASTON 1 PUNTO 8000", "Movilidad y Desplazamiento", 8000.0, ""),
                new ProductSeedData("BASTON PLEGABLE VIVE CON FOCO MOB1017BLK", "Movilidad y Desplazamiento", 23000.0, ""),
                new ProductSeedData("ANDADERA CON ASIENTO VIVE ROJA 180000", "Movilidad y Desplazamiento", 180000.0, ""),
                new ProductSeedData("Bastón de 4 Puntos VIVE", "Movilidad y Desplazamiento", 20000.0, ""),
                new ProductSeedData("BASTON DE 4 PUNTOS BASE GRANDE CAREX", "Movilidad y Desplazamiento", 17000.0, ""),
                new ProductSeedData("ZAPATO PRECAMINADOR IMPULSO ARENA/CAFE TALLA 19 25000", "Movilidad y Desplazamiento", 25000.0, ""),
                new ProductSeedData("ZAPATO PRECAMINADOR PINGO NEGRO  TALLA 19   25000", "Movilidad y Desplazamiento", 25000.0, ""),
                new ProductSeedData("BASTON 1 PUNTO PLATIADO  TLP", "Movilidad y Desplazamiento", 14500.0, ""),
                new ProductSeedData("ANDADERA ANTERIOR AMARILLA 70000", "Movilidad y Desplazamiento", 70000.0, ""),
                new ProductSeedData("BASTON 4 PUNTOS VIVE MORADO MOB1003PUR", "Movilidad y Desplazamiento", 18000.0, ""),
                new ProductSeedData("ZAPATO PRECAMINADOR PINGO NEGRO TALLA 18 25000", "Movilidad y Desplazamiento", 25000.0, ""),
                new ProductSeedData("BASTON 4 PUNTOS CAREX  20000", "Movilidad y Desplazamiento", 20000.0, ""),
                new ProductSeedData("ANDADERA 4 PUNTOS HOSP 48000 COLONES", "Movilidad y Desplazamiento", 48000.0, ""),
                new ProductSeedData("BASTON 4 PUNTOS VIVE AZUL 18000", "Movilidad y Desplazamiento", 18000.0, ""),
                new ProductSeedData("ZAPATO SENSASUAVE 607 TALLA 30", "Calzado Ortopédico", 64581.0, ""),
                new ProductSeedData("ZAPATO SENSASUAVE 606C TALLA 26", "Calzado Ortopédico", 50000.0, ""),
                new ProductSeedData("ZAPATO SENSASUAVE 606B TALLA 28", "Calzado Ortopédico", 50000.0, ""),
                new ProductSeedData("ZAPATO ADDICTION NEGRO ESTILO 403 TALLA 24", "Calzado Ortopédico", 50000.0, ""),
                new ProductSeedData("ZAPATO ADDICTION  NEGRO ESTILO 871 TALLA 24   53000", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ZAPATO ADDICTION ESTILO 5055 TALLA 24  53000", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ZAPATO BIO SHOES NEGRO TALLA 27 45000", "Calzado Ortopédico", 45000.0, ""),
                new ProductSeedData("ZAPATO ORTOSPORT AZUL TALLA 28 43000", "Calzado Ortopédico", 43000.0, ""),
                new ProductSeedData("ZAPATO BIO SHOES ESTILO E-5158 TALLA 24  45000", "Calzado Ortopédico", 45000.0, ""),
                new ProductSeedData("ZAPATO ORTOSPORT NEGRO TALLA 33  6027.TF05  33000", "Calzado Ortopédico", 43000.0, ""),
                new ProductSeedData("ZAPATO ORTOSPORT NEGRO TALLA 33   33000", "Calzado Ortopédico", 33000.0, ""),
                new ProductSeedData("ZAPATO BIO SHOES TALLA 24  45000", "Calzado Ortopédico", 45000.0, ""),
                new ProductSeedData("ZAPATO CLINICUS  TALLA 24 57000", "Calzado Ortopédico", 57000.0, ""),
                new ProductSeedData("ZAPATO SANDY TALLA 31  43000", "Calzado Ortopédico", 43000.0, ""),
                new ProductSeedData("ZAPATO ADDICTION TALLA 28 ESTILO 365  53000", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("CORRECTOR DE JUANETE VIVE  GRIS", "Calzado Ortopédico", 15000.0, ""),
                new ProductSeedData("zapatos omena talla  negro 24  570000", "Calzado Ortopédico", 57000.0, ""),
                new ProductSeedData("ZAPATO CLINICUS AZUL TALLA 25 58000", "Calzado Ortopédico", 58000.0, ""),
                new ProductSeedData("ZAPATO ADDICTION NEGRO ESTILO 403 TALLA 25.5", "Calzado Ortopédico", 50000.0, ""),
                new ProductSeedData("SEPARADOR DE DEDOS DE GEL 4500", "Calzado Ortopédico", 4500.0, ""),
                new ProductSeedData("CORRECTOR DE JUANETE VIVE NEGRO SUP2066BLK", "Calzado Ortopédico", 15000.0, ""),
                new ProductSeedData("ZAPATO  ADDICTION NEGRO ESTILO 431 TALLA 25.5 50000", "Calzado Ortopédico", 50000.0, ""),
                new ProductSeedData("ZAPATO ORTOSPORT BLANCO/ ROSA TALLA 33 33000", "Calzado Ortopédico", 33000.0, ""),
                new ProductSeedData("ZAPATO BIO SHOES NEGRO TALLA 26 45000", "Calzado Ortopédico", 45000.0, ""),
                new ProductSeedData("ZAPATO ORTOSPORT ESTILO 6027.TF05  TALLA 31", "Calzado Ortopédico", 33000.0, ""),
                new ProductSeedData("ZAPATO ADDICTION NEGRO TALLA 27  53000", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ZAPATO ZANDOMI TALLA 26  53000", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ZAPATO ONENA CAFE TALLA 25 58000", "Calzado Ortopédico", 58000.0, ""),
                new ProductSeedData("ZAPATO BIO SHOES  TALLA 26", "Calzado Ortopédico", 45000.0, ""),
                new ProductSeedData("ZAPATO ADDICTION TALLA 25   52000", "Calzado Ortopédico", 52000.0, ""),
                new ProductSeedData("ZAPATO ORTOSPORT  BLANCO CON AZUL  25", "Calzado Ortopédico", 40000.0, ""),
                new ProductSeedData("KIT PARA JUANETE VIVE INS1034", "Calzado Ortopédico", 10000.0, ""),
                new ProductSeedData("ZAPATO SENSASUAVE 680 NEGRO TALLA 23", "Calzado Ortopédico", 50000.0, ""),
                new ProductSeedData("ZAPATO BIO SHOES NEGRO TALLA 26   45000", "Calzado Ortopédico", 45000.0, ""),
                new ProductSeedData("ZAPATO NEGRO NEOPRENO TALLA  25  ESTILO  E-5117", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ZAPATO ADDICTION NEGRO TALLA 23.5  53000", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ZAPATO ADDICTION NEGRO TALLA 28.5  53000", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ZAPATO NEGRO AWWA TALLA 25  53000", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ZAPATOS SANDY TALLA 28 V9104", "Calzado Ortopédico", 43000.0, ""),
                new ProductSeedData("SEPARADOR DEDOS UNIVERSAL TALLA L    5000", "Calzado Ortopédico", 5000.0, ""),
                new ProductSeedData("CORRECTOR JUANETE BEIS VIVE SUP2066BGE", "Calzado Ortopédico", 15000.0, ""),
                new ProductSeedData("ZAPATO SENSASUIAVE 644 TALLA 25", "Calzado Ortopédico", 50000.0, ""),
                new ProductSeedData("ZAPATO ORTOSPORT NEGRO TALLA 32  6027.TF05  33000", "Calzado Ortopédico", 33000.0, ""),
                new ProductSeedData("ZAPATO ADDICTION NEGRO TALLA 26.5  53000", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ZAPATO ORTOSPORT AZUL TALLA 36  37000", "Calzado Ortopédico", 37000.0, ""),
                new ProductSeedData("ZAPATOS ADDICTION TO COMFORT ESTILO 407 TALLA 23 NEGRO 52000", "Calzado Ortopédico", 52000.0, ""),
                new ProductSeedData("ZAPATO ADDICTION ESTILO 403 TALLA 23.5   53000", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ZAPATO ADDITION ESTILO 871 TALLA 23 53000", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ZAPATO ADDICTION ESTILO 431 24  53000", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ZAPATO SENSASUAVE 606 TALLA 30", "Calzado Ortopédico", 50000.0, ""),
                new ProductSeedData("ZAPATO CLINICUS NEGRO ESTILO 9081 TALLA 25 58000", "Calzado Ortopédico", 58000.0, ""),
                new ProductSeedData("ZAOATO ADDICTION ESTILO 390 TALLA 28  53000", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ZAPATO BIO SHOES E 5728 TALLA 43     45000", "Calzado Ortopédico", 22500.0, ""),
                new ProductSeedData("ZAPATOS ORTOSPORT  TALLA 33 NEGRO 43000", "Calzado Ortopédico", 43000.0, ""),
                new ProductSeedData("ZAPATO BIO SHOES  TALLA  41   45000", "Calzado Ortopédico", 45000.0, ""),
                new ProductSeedData("ZAPATO NEGRO ORTO TECH TALLA 35 28000", "Calzado Ortopédico", 14000.0, ""),
                new ProductSeedData("ZAPATO CLINICUS NEGRO TALLA 24 58000", "Calzado Ortopédico", 58000.0, ""),
                new ProductSeedData("ZAPATO ORTOSPORT AZUL TALLA 35  37000", "Calzado Ortopédico", 37000.0, ""),
                new ProductSeedData("zapato ADDICTION  ESTILO 217 TALLA 24  53000", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ZAPATO ADDICTION NEGRO TALLA 26", "Calzado Ortopédico", 53000.0, ""),
                new ProductSeedData("ALMOHADA ANATÓMICA PEQUEÑA", "Cuidado en Casa y Vida Diaria", 13000.0, ""),
                new ProductSeedData("COMPRESA COJÍN LUMBAR", "Cuidado en Casa y Vida Diaria", 21000.0, ""),
                new ProductSeedData("GUANTE  AMES WALKER 15-20mmHg  TALLA M  8500", "Cuidado en Casa y Vida Diaria", 8500.0, ""),
                new ProductSeedData("ICONTINENCE PAD VIVE GRIS", "Cuidado en Casa y Vida Diaria", 18370.0, ""),
                new ProductSeedData("BOLA DE FOAM AMARILLA", "Cuidado en Casa y Vida Diaria", 5000.0, ""),
                new ProductSeedData("ALMOHADA ANATOMICA PROURSA", "Cuidado en Casa y Vida Diaria", 24000.0, ""),
                new ProductSeedData("DONA INFLABLE CAREX ROJA", "Cuidado en Casa y Vida Diaria", 20394.0, ""),
                new ProductSeedData("SILLA BAÑO BLANCA CAREX", "Cuidado en Casa y Vida Diaria", 45000.0, ""),
                new ProductSeedData("ACEITE EN GEL", "Cuidado en Casa y Vida Diaria", 5500.0, ""),
                new ProductSeedData("ALFOMBRA ANTIDESLIZANTE CAREX", "Cuidado en Casa y Vida Diaria", 11330.0, ""),
                new ProductSeedData("BIDE PLASTICO CELESTE MEDLINE   8000", "Cuidado en Casa y Vida Diaria", 8000.0, ""),
                new ProductSeedData("BOLA FOAM ROJA", "Cuidado en Casa y Vida Diaria", 8000.0, ""),
                new ProductSeedData("CREMA CORPORAL 5500", "Cuidado en Casa y Vida Diaria", 5500.0, ""),
                new ProductSeedData("COJIN DRIVE CON GEL 18\"W X 16\"D X 2\"H   30000", "Cuidado en Casa y Vida Diaria", 30000.0, ""),
                new ProductSeedData("COJIN DRIVE CON GEL   16\"WX 16\"D X 2\" H  25000", "Cuidado en Casa y Vida Diaria", 25000.0, ""),
                new ProductSeedData("COJIN DRIVE DE GEL  20\"W X 16\"d X 2\"H  35000", "Cuidado en Casa y Vida Diaria", 35000.0, ""),
                new ProductSeedData("COBERTOR SILLON IMPERMEABLE", "Cuidado en Casa y Vida Diaria", 60000.0, ""),
                new ProductSeedData("CREMA CORPORAL ANTIOXIDANTE   7000", "Cuidado en Casa y Vida Diaria", 7000.0, ""),
                new ProductSeedData("DONA CAREX AZUL", "Cuidado en Casa y Vida Diaria", 15000.0, ""),
                new ProductSeedData("COJIN INFLABLE ANTIESCARAS  AZUL 17000", "Cuidado en Casa y Vida Diaria", 17000.0, ""),
                new ProductSeedData("BARRA 12PULGADAS CAREX 17136", "Cuidado en Casa y Vida Diaria", 19260.0, ""),
                new ProductSeedData("TIJERA GAINWELL  20000", "Cuidado en Casa y Vida Diaria", 20000.0, ""),
                new ProductSeedData("CUÑA MEDICA PROURSA 70X20", "Cuidado en Casa y Vida Diaria", 22000.0, ""),
                new ProductSeedData("CREMA PARA PREVENIR PAÑALITIS    5500", "Cuidado en Casa y Vida Diaria", 8000.0, ""),
                new ProductSeedData("COJIN MASAJES PROURSA  12X60  22000", "Cuidado en Casa y Vida Diaria", 22000.0, ""),
                new ProductSeedData("GUANTE COMPRESION 20-30mmHg  TALLA XL 8500", "Cuidado en Casa y Vida Diaria", 8500.0, ""),
                new ProductSeedData("SILLA BAÑO GRIS 3 EN 1 VIVE CON APOYA PIES", "Cuidado en Casa y Vida Diaria", 95000.0, ""),
                new ProductSeedData("RIÑONERA ACERO INOXIDABLE", "Cuidado en Casa y Vida Diaria", 15000.0, ""),
                new ProductSeedData("COLCHON ESTERA DE GEL INDIVIDUAL", "Cuidado en Casa y Vida Diaria", 110000.0, ""),
                new ProductSeedData("ALMOHADA MULTI GEL CON CURVATURA (ANATOMICA)", "Cuidado en Casa y Vida Diaria", 31000.0, ""),
                new ProductSeedData("SILLA BAÑO VIVE GRIS  80000", "Cuidado en Casa y Vida Diaria", 40000.0, ""),
                new ProductSeedData("DONA FOAM CUSHION CAREX", "Cuidado en Casa y Vida Diaria", 17000.0, ""),
                new ProductSeedData("RODILLERA BARRAS LATERALES NEGRA (S) SUP3032BLKS", "Cuidado en Casa y Vida Diaria", 10000.0, ""),
                new ProductSeedData("SILLA BAÑO BLANCA CAREX", "Cuidado en Casa y Vida Diaria", 35000.0, ""),
                new ProductSeedData("SHAMPOO CORPORAL  5500", "Cuidado en Casa y Vida Diaria", 5500.0, ""),
                new ProductSeedData("SCOOPER BOWL  10000", "Cuidado en Casa y Vida Diaria", 10000.0, ""),
                new ProductSeedData("BASE SILLA ANCLA", "Cuidado en Casa y Vida Diaria", 375000.0, ""),
                new ProductSeedData("RODILLERA BARRAS LATERALES VIVE NEGRA  TALLA M", "Cuidado en Casa y Vida Diaria", 20000.0, ""),
                new ProductSeedData("GEL FRIÓ- CALOR 7000", "Rehabilitación y Terapia Física", 7931.0, ""),
                new ProductSeedData("DEDO FRIO-CALOR  TALLA S  7000", "Rehabilitación y Terapia Física", 7000.0, ""),
                new ProductSeedData("CASCO FRIO-CALOR", "Rehabilitación y Terapia Física", 20000.0, ""),
                new ProductSeedData("INTENSITY  10  65000", "Rehabilitación y Terapia Física", 65000.0, ""),
                new ProductSeedData("TENS DIGITAL UNIT  VIVE", "Rehabilitación y Terapia Física", 35000.0, ""),
                new ProductSeedData("TENS DIGITAL MASSAGER", "Rehabilitación y Terapia Física", 35000.0, ""),
                new ProductSeedData("AUTOMATIC BLOOD PRESSURE MONITOR DRIVE", "Rehabilitación y Terapia Física", 29000.0, ""),
                new ProductSeedData("TUBO DE AGARRE DE ESPUMA VIVE 2500", "Rehabilitación y Terapia Física", 2832.5, ""),
                new ProductSeedData("CODERA FRIO-CALOR  25000", "Rehabilitación y Terapia Física", 25000.0, ""),
                new ProductSeedData("RODILLERA FRIO-CALOR   TALLA L/XL  27000", "Rehabilitación y Terapia Física", 27000.0, ""),
                new ProductSeedData("COMPRESA ELECTRICA VIVE 12X24", "Rehabilitación y Terapia Física", 24000.0, ""),
                new ProductSeedData("COMPRESA MASCARA-LINEA AZUL", "Rehabilitación y Terapia Física", 12000.0, ""),
                new ProductSeedData("BOLSA HIELO AZUL 18000", "Rehabilitación y Terapia Física", 20394.0, ""),
                new ProductSeedData("PLASTICINA THERA PUTTY TAN 2 OZ", "Rehabilitación y Terapia Física", 7364.5, ""),
                new ProductSeedData("BOLA TERAPEUTICA VERDE DE 65CM", "Rehabilitación y Terapia Física", 40000.0, ""),
                new ProductSeedData("MUÑEQUERA PALMAR FRIO-CALOR  25000", "Rehabilitación y Terapia Física", 25000.0, ""),
                new ProductSeedData("PLASTICINA THERA PUTTY AZUL 2 OZ", "Rehabilitación y Terapia Física", 7364.5, ""),
                new ProductSeedData("OXIMETRO DRIVE   32000", "Rehabilitación y Terapia Física", 0.0, ""),
                new ProductSeedData("ALMOHADILLA PARA FIEBRE", "Rehabilitación y Terapia Física", 7000.0, ""),
                new ProductSeedData("TWISTER NACIONAL  40000", "Rehabilitación y Terapia Física", 40000.0, ""),
                new ProductSeedData("LED COMPRESSION VIVE  350000", "Rehabilitación y Terapia Física", 350000.0, ""),
                new ProductSeedData("PLANCHAS DE GEL ADEHESIVO", "Rehabilitación y Terapia Física", 10000.0, ""),
                new ProductSeedData("CODERA CORTA S", "Soportes Ortopédicos", 13200.0, ""),
                new ProductSeedData("MUÑEQUERA ONE SIZE", "Soportes Ortopédicos", 8950.7, ""),
                new ProductSeedData("FAJA INTERCOSTAL XL", "Soportes Ortopédicos", 20394.0, ""),
                new ProductSeedData("MUÑEQUERA SIMPLE (BLACK LINE) T2 6000", "Soportes Ortopédicos", 6798.0, ""),
                new ProductSeedData("FERULA FASCITIS PLANTAR L", "Soportes Ortopédicos", 27500.0, ""),
                new ProductSeedData("CODERA TELESCOPICA DERECHA", "Soportes Ortopédicos", 101970.0, ""),
                new ProductSeedData("CODERA CORTA CON VELCRO T1 7500", "Soportes Ortopédicos", 9900.0, ""),
                new ProductSeedData("TOBILLERA CON SILICONA TALLA XL", "Soportes Ortopédicos", 16995.0, ""),
                new ProductSeedData("INMOVILIZADOR DE DEDO Y MUÑECA T3 IZ 19500", "Soportes Ortopédicos", 22093.5, ""),
                new ProductSeedData("MEDIA ANTIEMBOLICA 18mmHg   XL 7500", "Soportes Ortopédicos", 7500.0, ""),
                new ProductSeedData("INMOVILIZADOR DE MUÑECA LARGO DERECHO L", "Soportes Ortopédicos", 16900.0, ""),
                new ProductSeedData("MEDIA COMPRESION 20-30 mmHg TALLA XL  15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MEDIA COMPRESION CON ZIPPER 20/30mmHg talla XL 21000", "Soportes Ortopédicos", 21000.0, ""),
                new ProductSeedData("MEDIA ANTIEMBOLICA COLOR BEIS 15-20mmHG TALLA XL", "Soportes Ortopédicos", 11000.0, ""),
                new ProductSeedData("TOBILLERA ESTABILIZADORA AJUSTE EN VELCRO-XL", "Soportes Ortopédicos", 18128.0, "."),
                new ProductSeedData("TOBILLERA ESTABILIZADORA AJUSTE EN VELCRO-L", "Soportes Ortopédicos", 18128.0, ""),
                new ProductSeedData("CODERA CON VELCRO T1", "Soportes Ortopédicos", 13750.0, ""),
                new ProductSeedData("CODERA SIMPLE TALLA S 10000", "Soportes Ortopédicos", 11330.0, ""),
                new ProductSeedData("FAJA LUMBAR BALLENADA TALLA M", "Soportes Ortopédicos", 24000.0, ""),
                new ProductSeedData("CORSE SACRO EN M  evergreen", "Soportes Ortopédicos", 40000.0, ""),
                new ProductSeedData("SILLA TRANSPORTE PROBASIC  20 PULGADAS         183600", "Soportes Ortopédicos", 183600.0, ""),
                new ProductSeedData("RODILLERA CON SILICONA Y BALLENAS  TALLA M  22000", "Soportes Ortopédicos", 22000.0, ""),
                new ProductSeedData("CODERA CON SUJECCION TALLA L  20000", "Soportes Ortopédicos", 20000.0, ""),
                new ProductSeedData("MUÑEQUERA BOOMERANG    TALLA M   13000", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("MEDIA COMPRESION DEBAJO DE RODILLA 20-30mmHg TALLA XL  15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MANGA DE COMPRESION LYMPHEDEMA  20-30 mmHg   AMES  TALLA XL  24000", "Soportes Ortopédicos", 24000.0, ""),
                new ProductSeedData("CODERA CON SILICONA TALLA M  20000", "Soportes Ortopédicos", 20000.0, ""),
                new ProductSeedData("CODERA CON SILICONA T1", "Soportes Ortopédicos", 13500.0, ""),
                new ProductSeedData("MEDIA TIPO PANTY 15-20 SHEER SUPPORT TALLA TALLA  L 18000", "Soportes Ortopédicos", 18000.0, ""),
                new ProductSeedData("FAJA TRASPIRABLE POSTOPERATORIA XXL 30000", "Soportes Ortopédicos", 32000.0, ""),
                new ProductSeedData("FAJA ELASTICA SOFT POST-PARTO  TALLA S  20000", "Soportes Ortopédicos", 20000.0, ""),
                new ProductSeedData("FAJA ELASTICA SOFT POST - PARTO TALLA M  20000", "Soportes Ortopédicos", 20000.0, ""),
                new ProductSeedData("RHIZO HIT INMOVILIZADOR DE DEDO PULGAR M", "Soportes Ortopédicos", 14500.0, ""),
                new ProductSeedData("MEDIA COMPRESION 20-30mmHg LUXURY TALLA L 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("ESPALDERA POSTURAL S", "Soportes Ortopédicos", 18128.0, ""),
                new ProductSeedData("CHALECO DE HOMBRO (L) DERECHO BC1082", "Soportes Ortopédicos", 36256.0, ""),
                new ProductSeedData("CINCHA ROTULIANA (S) BC1159", "Soportes Ortopédicos", 10197.0, ""),
                new ProductSeedData("FAJA PARA COLOSTOMÍA DE 24 CM - XL BC1305", "Soportes Ortopédicos", 31724.0, ""),
                new ProductSeedData("INMOVILIZADOR DE CLAVICULA (L) BC1083", "Soportes Ortopédicos", 22660.0, ""),
                new ProductSeedData("MUSLERA SIMPLE BLACK LINE (S) BC1201E", "Soportes Ortopédicos", 12000.0, ""),
                new ProductSeedData("RODILLERA ABIERTA (S) BC1106E", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("RODILLERA ABIERTA (L) BC1106E", "Soportes Ortopédicos", 16500.0, ""),
                new ProductSeedData("RODILLERA ABIERTA (XL) BC1106E", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("RODILLERA ABIERTA (L) BC1106E", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("RODILLERA ROTULA CON VELCRO (XXL) BC1103E", "Soportes Ortopédicos", 10000.0, ""),
                new ProductSeedData("RODILLERA TUBULAR (S) BC1101", "Soportes Ortopédicos", 10706.85, ""),
                new ProductSeedData("GEMELERA  NEGRA (L) BC1853E", "Soportes Ortopédicos", 11330.0, ""),
                new ProductSeedData("MANGA AMES WALKER  15-20mmHg  TALLA L 8500", "Soportes Ortopédicos", 8500.0, ""),
                new ProductSeedData("MEDIA COMPRESION TIPO PANTY 15-20 mmHg  TALLA L 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MANGA AMES  20-30 mmHg  TALLA L 22000", "Soportes Ortopédicos", 22000.0, ""),
                new ProductSeedData("FAJA TRASPIRABLE POSTOPERATORIA XL 30000", "Soportes Ortopédicos", 33990.0, ""),
                new ProductSeedData("FAJA ELASTICA SOFT POST - PARTO  TALLA XL 20000", "Soportes Ortopédicos", 20000.0, ""),
                new ProductSeedData("TOBILLERA CON SILICONA TALLA S  18000", "Soportes Ortopédicos", 18000.0, ""),
                new ProductSeedData("ROM KNEE BRACE  VIVE", "Soportes Ortopédicos", 70000.0, ""),
                new ProductSeedData("MUÑEQUERA CON INMOV.DEDO PULG. T2 IZ 14000", "Soportes Ortopédicos", 15862.0, ""),
                new ProductSeedData("MEDIA 15/20 mm/Hg  sheer support closed toe  typo Panty  TALLA M 16000", "Soportes Ortopédicos", 16000.0, ""),
                new ProductSeedData("MEDIA COMPRESION DEBAJO DE RODILLA 15-20 mmHg  TALLA L  12000", "Soportes Ortopédicos", 12000.0, ""),
                new ProductSeedData("MEDIA ANTIEMBOLICA COLOR BEIS 15-20mmHG TALLA L 11000", "Soportes Ortopédicos", 11000.0, ""),
                new ProductSeedData("MEDIA TIPO PANTY 15-20 SHEER SUPPORT TALLA TALLA S 18000", "Soportes Ortopédicos", 18000.0, ""),
                new ProductSeedData("MEDIA DE COMPRESION CON ZIPPER  20-30mmHg  TALLA M 21000", "Soportes Ortopédicos", 21000.0, ""),
                new ProductSeedData("RHIZO HIT INMOVILIZADOR DE DEDO PULGAR  L", "Soportes Ortopédicos", 14500.0, ""),
                new ProductSeedData("MEDIA COMPRESION PANTY 20-30 mmHG TALLA M 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("COLOCADOR DE MEDIAS VENODONNER GRIS 42000", "Soportes Ortopédicos", 42000.0, ""),
                new ProductSeedData("MEDIA COMPRESION  PANTY 20-30 mmHg TALLA L  15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("INMOVILIZADOR DEDO INDIVIDUAL M", "Soportes Ortopédicos", 7150.0, ""),
                new ProductSeedData("INMOVILIZADOR DE MUÑECA LARGO DERECHO S", "Soportes Ortopédicos", 16900.0, ""),
                new ProductSeedData("FERULA PARA DEDO RANA  S - BLUNDING   6000", "Soportes Ortopédicos", 6000.0, ""),
                new ProductSeedData("MUSLERA ELASTICA TALLA L 8837", "Soportes Ortopédicos", 8837.0, ""),
                new ProductSeedData("INMOVILIZADOR DE MUÑECA CORTO S DERECHA", "Soportes Ortopédicos", 14500.0, ""),
                new ProductSeedData("RODILLERA ROTULA CON VELCRO (L) BC1103E", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("INMOVILIZADOR DE DEDO Y MUÑECA T1 IZ 19500", "Soportes Ortopédicos", 22093.5, ""),
                new ProductSeedData("COLLAR ESTABILIZADOR TIPO SHANZ CUELLO - M", "Soportes Ortopédicos", 15495.0, ""),
                new ProductSeedData("TOBILLERA SIMPLE BC1401E-M", "Soportes Ortopédicos", 7931.0, ""),
                new ProductSeedData("TOBILLERA SIMPLE BC1401E-XXL", "Soportes Ortopédicos", 7931.0, ""),
                new ProductSeedData("BANDA CERRADA AZUL 3400", "Soportes Ortopédicos", 3400.0, ""),
                new ProductSeedData("FAJA LUMBAR BALLENADA T1", "Soportes Ortopédicos", 31000.0, ""),
                new ProductSeedData("CINCHA P TENDON DE AQUILES MED 12000", "Soportes Ortopédicos", 13596.0, ""),
                new ProductSeedData("FERULA DE DESVIACION CUBITAL IZ (solo disponible lo de tienda)", "Soportes Ortopédicos", 8950.7, ""),
                new ProductSeedData("FAJA INTERCOSTAL M 18000", "Soportes Ortopédicos", 20394.0, ""),
                new ProductSeedData("RODILLERA CON ORIENTADOR LATERAL S IZ 20000", "Soportes Ortopédicos", 22660.0, ""),
                new ProductSeedData("VENDA ELÁSTICA DEPORTIVA", "Soportes Ortopédicos", 3800.0, ""),
                new ProductSeedData("FAJA SACRO LUMBAR  S", "Soportes Ortopédicos", 30800.0, ""),
                new ProductSeedData("FAJA SACRO LUMBAR L", "Soportes Ortopédicos", 30800.0, ""),
                new ProductSeedData("MEDIA VENOSAN 6000 UNISSES TALLA  L 20/30mmHg  16000", "Soportes Ortopédicos", 16000.0, ""),
                new ProductSeedData("MEDIA ANTIEMBOLIA  AMES WALKER 18mmHg Blanca al muslo TALLA L", "Soportes Ortopédicos", 11500.0, ""),
                new ProductSeedData("MEDIAS DE COMPRESION 8/18 ANTIEMBOLICA ATHLON BLANCAS TALLA L", "Soportes Ortopédicos", 11500.0, ""),
                new ProductSeedData("MUÑEQUERA CON INMOV.DEDO PULG. T3 DE 14000", "Soportes Ortopédicos", 15862.0, ""),
                new ProductSeedData("MUSLERA ELASTICA TALLA L  8837", "Soportes Ortopédicos", 8837.0, ""),
                new ProductSeedData("TOBILLERA CON SILICONA TALLA L", "Soportes Ortopédicos", 16995.0, ""),
                new ProductSeedData("MUÑEQUERA DEDO LIBRE (BLACK LINE) T2 8000", "Soportes Ortopédicos", 9064.0, ""),
                new ProductSeedData("MEDIA COMPRESION DEBAJO DE RODILLA 20-30mmHg TALLA L  15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("RODILLERA CON ARTICULACIÓN POLICÉNTRICA XL", "Soportes Ortopédicos", 75000.0, ""),
                new ProductSeedData("SEPARADOR DE GEL DE DEDOS L LENOX 5000", "Soportes Ortopédicos", 5000.0, ""),
                new ProductSeedData("CODERA CON SILICONA TALLA M 15000", "Soportes Ortopédicos", 16995.0, ""),
                new ProductSeedData("MEDIA COMPRESION CON ZIPPER 20/30 mmHg talla L  21000", "Soportes Ortopédicos", 21000.0, ""),
                new ProductSeedData("MUSLERA ELASTICA TALLA S  8837", "Soportes Ortopédicos", 8837.0, ""),
                new ProductSeedData("CORSE SACRO FLEXIBLE PEDIATRICO 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("BOLA  TERAPEUTICA CANDO  AZUL  85 CM", "Soportes Ortopédicos", 60000.0, ""),
                new ProductSeedData("MEDIA PARA AFO  O KAFO ADULTO", "Soportes Ortopédicos", 0.0, ""),
                new ProductSeedData("CORSE SACRO EN M   evergreen", "Soportes Ortopédicos", 0.0, ""),
                new ProductSeedData("MEDIA COMPRESION DEPORTIVA BLANCA 8-15mmHg TALLA M 12000", "Soportes Ortopédicos", 12000.0, ""),
                new ProductSeedData("ESPALDARA  ELASTICO MEDIANO", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("FAJA ELASTICA SOFT POST - PARTO TALLA L  20000", "Soportes Ortopédicos", 14000.0, ""),
                new ProductSeedData("FERULA STAXX TALLA 6 2500", "Soportes Ortopédicos", 2500.0, ""),
                new ProductSeedData("CORSE  DORSO LUMBAR CONFORTAL MEDICAL LXL", "Soportes Ortopédicos", 43000.0, ""),
                new ProductSeedData("MEDIA COMPRESION TIPO PANTY 20-30 mmHg talla XL 28000", "Soportes Ortopédicos", 28000.0, ""),
                new ProductSeedData("MEDIA COMPRESION MEDICAL 20-30mmHg  talla XXL 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MANGA DE COMPRESION LYMPHEDEMA  20-30 mmHg   AMES  TALLA M  24000", "Soportes Ortopédicos", 24000.0, ""),
                new ProductSeedData("MEDIA COMPRESION 20-30 TALLA 10-12  COLOR TAUPE", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("MEDICAL COMPRESSION HOSIERY CURAD  20/30mmHG  16000", "Soportes Ortopédicos", 16000.0, ""),
                new ProductSeedData("FERULA FASCITIS PLANTAR VIVE XL", "Soportes Ortopédicos", 27000.0, ""),
                new ProductSeedData("MEDIA TIPO PANTY 20-30mmHG TALLA M   28000 PUNTERA ABIERTA", "Soportes Ortopédicos", 28000.0, ""),
                new ProductSeedData("FAJA ELASTICA  POST-PARTO 24CM/28CM TALLA S   23000", "Soportes Ortopédicos", 23000.0, ""),
                new ProductSeedData("MEDIA TIPO PANTY 15-20 SHEER SUPPORT TALLA TALLA  XL 18000", "Soportes Ortopédicos", 17999.0, ""),
                new ProductSeedData("MEDIA ANTIEMBOLICA BLANCA 18 mmHg  TALLA  XL 7500", "Soportes Ortopédicos", 7500.0, ""),
                new ProductSeedData("MEDIA TIPO PANTY 20/30  mmHg  AMES  TALLA L 25000", "Soportes Ortopédicos", 25000.0, ""),
                new ProductSeedData("MEDICAL SUPPORT OPEN TOE KNNE HIGHS  TALLA M 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MEDIA  COOLMAX  OVER THE  CALF SOCKS  TALLA  XL 15000", "Soportes Ortopédicos", 7500.0, ""),
                new ProductSeedData("CINCHA ROTULIANA DOBLE (M) BC1160", "Soportes Ortopédicos", 15500.0, ""),
                new ProductSeedData("FAJA PARA COLOSTOMÍA DE 24 CM (L) BC1305", "Soportes Ortopédicos", 31724.0, ""),
                new ProductSeedData("GEMELERA NEGRA (M) BC1853", "Soportes Ortopédicos", 11330.0, ""),
                new ProductSeedData("GEMELERA TUBULAR NEGRA (S) BC1853E", "Soportes Ortopédicos", 11330.0, ""),
                new ProductSeedData("HOMBRERA DELTOIDES (S) BC1088", "Soportes Ortopédicos", 31724.0, ""),
                new ProductSeedData("MUSLERA SIMPLE BLACK LINE (M) BC1201E", "Soportes Ortopédicos", 12000.0, ""),
                new ProductSeedData("RODILLERA ARTICULADA CORTA CON VELCRO (S) BC1105E", "Soportes Ortopédicos", 28000.0, ""),
                new ProductSeedData("RODILLERA ARTICULADA CORTA CON VELCRO (M)  BC1105E", "Soportes Ortopédicos", 28000.0, ""),
                new ProductSeedData("RODILLERA SOSTEN ROTULIANO (S) BC1102", "Soportes Ortopédicos", 10763.5, ""),
                new ProductSeedData("RODILLERA ROTULIANA  (XXL) BC1102E", "Soportes Ortopédicos", 9700.0, ""),
                new ProductSeedData("RODILLERA ROTULIANA (S) BC1102E", "Soportes Ortopédicos", 9700.0, ""),
                new ProductSeedData("RODILLERA BALLENADA CON VELCRO (L) BC1104", "Soportes Ortopédicos", 18128.0, ""),
                new ProductSeedData("RODILLERA BALLENADA CON VELCRO (L) BC1104E", "Soportes Ortopédicos", 11000.0, ""),
                new ProductSeedData("RODILLERA ROTULA CON VELCRO (M) BC1103E", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("RODILLERA TUBULAR (XL) BC1101", "Soportes Ortopédicos", 10706.0, ""),
                new ProductSeedData("RODILLERA ARTICULADA CORTA CON VELCRO (M) BC1105", "Soportes Ortopédicos", 35123.0, ""),
                new ProductSeedData("MEDIAS COMPRESION ANTIEMBOLICAS CERRADAS TALLA M 18mmHg   15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("ESPALDERA POSTURAL M", "Soportes Ortopédicos", 18128.0, ""),
                new ProductSeedData("MEDIA COMPRESION E-Z WALKER 8-15 mmHg talla S 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MEDIA COMPRESION E-Z WALKER 8-15 mmHg talla XL 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MEDIA COMPRESION TIPO PANTY 15-20mmHg  TALLA XL 16000", "Soportes Ortopédicos", 16000.0, ""),
                new ProductSeedData("MEDIA COMPRESION TIPO PANTY 15-20 mmHg  15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("SOPORTE PIE CAIDO  TALLA S 32000", "Soportes Ortopédicos", 32000.0, ""),
                new ProductSeedData("FERULA PARA DEDO RANA  M - BLUNDING   6000", "Soportes Ortopédicos", 6000.0, ""),
                new ProductSeedData("MUÑEQUERA CON DEDO LIBRE DOBLE AJUSTE", "Soportes Ortopédicos", 10000.0, ""),
                new ProductSeedData("MEDIA PARA DIABETICOS AMES  NEGRAS  L/XL   10000", "Soportes Ortopédicos", 10000.0, ""),
                new ProductSeedData("COLLAR CERVICAL BLANDO  CONFORTAL MEDICAL S/M CM1003", "Soportes Ortopédicos", 13029.5, ""),
                new ProductSeedData("RODILLERA ROTULA CON VELCRO (XL) BC1103E", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("MUÑEQUERA SIMPLE (BLACK LINE) T4 6000", "Soportes Ortopédicos", 6798.0, ""),
                new ProductSeedData("MEDIA COMPRESION  20-30 TALLA 9-11 NEGRO", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("TOBILLERA CON SUJECION T1", "Soportes Ortopédicos", 20000.0, ""),
                new ProductSeedData("MUÑEQUERA DEDO LIBRE (BLACK LINE) T3 8000", "Soportes Ortopédicos", 9064.0, ""),
                new ProductSeedData("TOBILLERA DEPORTIVA RUNNER T4 15000", "Soportes Ortopédicos", 15895.0, ""),
                new ProductSeedData("MEDIA MEDIA COMPRESION TIPO PANTY 15-20 mmHg  talla L", "Soportes Ortopédicos", 16000.0, ""),
                new ProductSeedData("MANGA AMES 15-20 mmHg TALLA M  22000", "Soportes Ortopédicos", 22000.0, ""),
                new ProductSeedData("MUÑEQUERA CON INMOV.DEDO PULG. T3 IZ 14000", "Soportes Ortopédicos", 15862.0, ""),
                new ProductSeedData("TOBILLERA ELASTICA T1 6000", "Soportes Ortopédicos", 6798.0, ""),
                new ProductSeedData("MEDIA AMES  GRADUATE 20/30mmHg TALLA L NUDE", "Soportes Ortopédicos", 16000.0, ""),
                new ProductSeedData("ESPALDERA PREMIUM L 17000", "Soportes Ortopédicos", 20394.0, ""),
                new ProductSeedData("CODERA CON SILICONA TALLA S 15000", "Soportes Ortopédicos", 16995.0, ""),
                new ProductSeedData("CODERA CORTA CON VELCRO T3 7500", "Soportes Ortopédicos", 8497.5, ""),
                new ProductSeedData("TOBILLERA ESTABILIZADORA AJUSTE EN VELCRO-M", "Soportes Ortopédicos", 18128.0, ""),
                new ProductSeedData("TOBILLERA CON SUJECION T2", "Soportes Ortopédicos", 20000.0, ""),
                new ProductSeedData("CODERA CON SILICONA T2", "Soportes Ortopédicos", 13500.0, ""),
                new ProductSeedData("MUÑEQUERA DEDO LIBRE DOBLE AJUSTABLE M 10000", "Soportes Ortopédicos", 10000.0, ""),
                new ProductSeedData("MUÑEQUERA CON DEDO PULGAR EN S", "Soportes Ortopédicos", 9064.0, ""),
                new ProductSeedData("FAJA INTERCOSTAL TALLA XXL 18000", "Soportes Ortopédicos", 20394.0, ""),
                new ProductSeedData("TOBILLERA ESTABILIZADORA AJUSTE EN VELCRO-S", "Soportes Ortopédicos", 18128.0, ""),
                new ProductSeedData("MUNEQUERA CON DEDO PULGAR LARGE", "Soportes Ortopédicos", 9500.0, ""),
                new ProductSeedData("INMOVILIZADOR MUÑECA Y DEDOS L   32000", "Soportes Ortopédicos", 32000.0, ""),
                new ProductSeedData("TOBILLERA CON SILICONA  TALLA M   18000", "Soportes Ortopédicos", 18000.0, ""),
                new ProductSeedData("SILLA FULL ORTOPEDICA INVACRE  18 PULGADAS   290000", "Soportes Ortopédicos", 290000.0, ""),
                new ProductSeedData("SILLA TRANSFERENCIA ELECTRICA PARA BAÑO", "Soportes Ortopédicos", 600000.0, ""),
                new ProductSeedData("FERULA STAXX   TALLA 2", "Soportes Ortopédicos", 2500.0, ""),
                new ProductSeedData("CODERA ARTICULADA 35000", "Soportes Ortopédicos", 39655.0, ""),
                new ProductSeedData("FERULA STAXX TALLA 5  2500", "Soportes Ortopédicos", 2500.0, ""),
                new ProductSeedData("CODERA SIMPLE TALLA M 10000", "Soportes Ortopédicos", 11500.0, ""),
                new ProductSeedData("CODERA CON VELCRO T2", "Soportes Ortopédicos", 13750.0, ""),
                new ProductSeedData("MANGA DE COMPRESION LYMPHEDEMA 20-30 mmHg AMES TALLA SMOLL 24000", "Soportes Ortopédicos", 24000.0, ""),
                new ProductSeedData("MANGA DE COMPRESION LYMPHEDEMA  20-30 mmHg   AMES  TALLA M 24000", "Soportes Ortopédicos", 24000.0, ""),
                new ProductSeedData("MEDIA COMPRESION LEOTARDO 20-30mmHg L 26000", "Soportes Ortopédicos", 26000.0, ""),
                new ProductSeedData("MEDICAL SUPPORT OPEN TOE KNNE HIGHS TALLA XL", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MEDIA COMPRESION TIPO PANTY 20-30  TALLA XL 25000", "Soportes Ortopédicos", 25000.0, ""),
                new ProductSeedData("BANDA TERABAN BEIS 3400", "Soportes Ortopédicos", 3400.0, ""),
                new ProductSeedData("MEDIA COMPRESION  UNISEX COTTON  20-30 mmHg TALLA L 12000", "Soportes Ortopédicos", 12000.0, ""),
                new ProductSeedData("INMOBILIZADOR DE MUÑECA LARGO AMBIDIESTRO- L 16000", "Soportes Ortopédicos", 18128.0, ""),
                new ProductSeedData("ESPALDERA PREMIUM S 18000", "Soportes Ortopédicos", 20394.0, ""),
                new ProductSeedData("INMOVILIZADOR DEDO INDIVIDUAL L", "Soportes Ortopédicos", 7150.0, ""),
                new ProductSeedData("MANGA DE COMPRESION LYMPHEDEMA  20-30 mmHg   AMES  TALLA L 24000", "Soportes Ortopédicos", 24000.0, ""),
                new ProductSeedData("MEDIA LEOTARDO PARA HOMBRE 20-30mmHg TALLA XL 26000", "Soportes Ortopédicos", 26000.0, ""),
                new ProductSeedData("MEDIA COMPRESION DEBAJO DE RODILLA 15-20mmHg TALLA M  12000", "Soportes Ortopédicos", 12000.0, ""),
                new ProductSeedData("INMOVILIZADOR DE MUÑECA LARGO L IZQUIERDO", "Soportes Ortopédicos", 16900.0, ""),
                new ProductSeedData("MEDIA COMPRESION  E-Z WALKER PLUS DIABETIC 8-15mmHg 7500", "Soportes Ortopédicos", 7500.0, ""),
                new ProductSeedData("MUÑEQUERA SIMPLE (BLACK LINE) T1 6000", "Soportes Ortopédicos", 6798.0, ""),
                new ProductSeedData("MEDIA COMPRESION DEPORTIVA BALNCA  8-15mmHg  TALLA L  12000", "Soportes Ortopédicos", 12000.0, ""),
                new ProductSeedData("MEDIA ANTIEMBOLICA  18 mmHg  TALLA M  7500", "Soportes Ortopédicos", 11000.0, ""),
                new ProductSeedData("INMOVILIZADOR DE MUÑECA LARGO S IZQUIERDO", "Soportes Ortopédicos", 16900.0, ""),
                new ProductSeedData("MEDIA COMPRESION TIPO PANTY 15-20 mmHg talla M   15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MEDIA TIPO PANTY 20-30mmHg talla M 15000", "Soportes Ortopédicos", 28000.0, ""),
                new ProductSeedData("CINCHA ROTULIANA DOBLE (S) BC1160", "Soportes Ortopédicos", 15500.0, ""),
                new ProductSeedData("CHALECO DE HOMBRO (L)  IZQUIERDO BC1082", "Soportes Ortopédicos", 36256.0, ""),
                new ProductSeedData("CINCHA ROTULIANA (M) BC1159", "Soportes Ortopédicos", 10197.0, ""),
                new ProductSeedData("FAJA PARA COLOSTOMÍA DE 28 CM (S) BC1305A", "Soportes Ortopédicos", 31724.0, ""),
                new ProductSeedData("FAJA PARA COLOSTOMÍA DE 24 CM  (S) BC1305", "Soportes Ortopédicos", 31724.0, ""),
                new ProductSeedData("INMOVILIZADOR DE CLAVICULA AJUSTABLE CONFORT MEDICAL CM1006", "Soportes Ortopédicos", 14162.5, ""),
                new ProductSeedData("MUSLERA SIMPLE BLACK LINE (XL) BC1201E", "Soportes Ortopédicos", 12000.0, ""),
                new ProductSeedData("RODILLERA ARTICULADA CORTA CON VELCRO (L) BC1105E", "Soportes Ortopédicos", 28000.0, ""),
                new ProductSeedData("RODILLERA ARTICULADA CORTA CON VELCRO (L) BC1105", "Soportes Ortopédicos", 35123.0, ""),
                new ProductSeedData("RODILLA ARTICULADA CORTA CON VELCRO (XL) BC1105", "Soportes Ortopédicos", 35123.0, ""),
                new ProductSeedData("RODILLERA SOSTEN ROTULIANO (L) BC1102", "Soportes Ortopédicos", 10763.5, ""),
                new ProductSeedData("RODILLERA BALLENADA CON VELCRO (XL) BC1104", "Soportes Ortopédicos", 18128.0, ""),
                new ProductSeedData("RODILLERA BALLENADA CON VELCRO (S) BC1104", "Soportes Ortopédicos", 18128.0, ""),
                new ProductSeedData("RODILLERA TUBULAR CONFORTA MEDICAL (S/M) CM1007", "Soportes Ortopédicos", 7931.0, ""),
                new ProductSeedData("RODILLERA TUBULAR (L) BC1101", "Soportes Ortopédicos", 10706.85, ""),
                new ProductSeedData("MEDIAS ANTIEMBOLICA  PUNTA CERRADA TALLA L  18mmHg 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MEDIAS COMPRESION DEPORTIVA  BLANCA 8-15mmHg    TALLA XL  12000", "Soportes Ortopédicos", 12000.0, ""),
                new ProductSeedData("MEDIA 8-15mmHg talla L coolmax over-the -calf socks  12000", "Soportes Ortopédicos", 12000.0, ""),
                new ProductSeedData("RODILLERA ARTICULADA CORTA CON VELCRO (XXL) BC1105", "Soportes Ortopédicos", 35123.0, ""),
                new ProductSeedData("INMOVILIZADOR DE MUNECA CORTO S IZQ", "Soportes Ortopédicos", 14500.0, ""),
                new ProductSeedData("MEDIA COMPRESION  E-Z WALKER 8-15 mmHg  talla M  15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MUÑEQUERA CON VELCRO T1", "Soportes Ortopédicos", 10140.35, ""),
                new ProductSeedData("RODILLERA ABIERTA (M) BC1106", "Soportes Ortopédicos", 16500.0, ""),
                new ProductSeedData("SOPORTE HERNIA INGUINAL TALLA S  28325", "Soportes Ortopédicos", 28325.0, ""),
                new ProductSeedData("FERULA PARA DEDO RANA  L - BLUNDING  6000", "Soportes Ortopédicos", 6000.0, ""),
                new ProductSeedData("INMOVILIZADOR DE DEDO Y MUÑECA T2 IZ 19500", "Soportes Ortopédicos", 22093.5, ""),
                new ProductSeedData("ESTABILIZADOR ESCAPULOHUMERAL (M) BC1081", "Soportes Ortopédicos", 29458.0, ""),
                new ProductSeedData("SOPORTE PIE CAIDO L  28000", "Soportes Ortopédicos", 28000.0, ""),
                new ProductSeedData("CODERA CON SILICONA T3 13000", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("MEDIA COMPRESION E-Z WALKER 8-15 mmHg talla L 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MEDIA COMPRESION 20-30  TALLA 10-12 NEGRA", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("MEDIA DE COMPRESION MARFIL 20-30  TALLA  9-11   13000", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("MUÑEQUERA SIMPLE (BLACK LINE) T3 6000", "Soportes Ortopédicos", 6798.0, ""),
                new ProductSeedData("TOBILLERA ELASTICA T3 6000", "Soportes Ortopédicos", 6798.0, ""),
                new ProductSeedData("MANGA AMES 20-30 mmHg  TALLA M  22000", "Soportes Ortopédicos", 22000.0, ""),
                new ProductSeedData("CORSE SACRO LUMBAR RIGIDO XXL 30000", "Soportes Ortopédicos", 30000.0, ""),
                new ProductSeedData("ESPALDERA PREMIUM M18000", "Soportes Ortopédicos", 20394.0, ""),
                new ProductSeedData("RODILLERA STABILIZING  KNEE SLEEVE", "Soportes Ortopédicos", 20000.0, ""),
                new ProductSeedData("MEDIA DE COMPRESION LUXURY OPAQUE CLOSED TOE  20-30mmHg  M", "Soportes Ortopédicos", 8000.0, ""),
                new ProductSeedData("CODERA CON SUJECCION TALLA M 14000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("CODERA SIMPLE TALLA L 10000", "Soportes Ortopédicos", 11500.0, ""),
                new ProductSeedData("CORSE DORSO RIGIDO BLANCO MEDIPAR  SMOLL", "Soportes Ortopédicos", 40000.0, ""),
                new ProductSeedData("MEDIA TIPO PANTY 20-30 mmHg talla L", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("SILLA TRANSPORTE LIGERA 130000", "Soportes Ortopédicos", 130000.0, ""),
                new ProductSeedData("FAJA INTERCOSTAL TALLA S 18000", "Soportes Ortopédicos", 20394.0, ""),
                new ProductSeedData("ESPALDERA ELÁSTICA  L", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("FERULA STAXX TALLA 4 2500", "Soportes Ortopédicos", 2500.0, ""),
                new ProductSeedData("TOBILLERA CON SUJECION T4", "Soportes Ortopédicos", 20000.0, ""),
                new ProductSeedData("FERULA FASCITIS PLANTAR VIVE M", "Soportes Ortopédicos", 27000.0, ""),
                new ProductSeedData("MEDIA ANTIEMBOLICA   TALLA L  15-20 mmHg 11000", "Soportes Ortopédicos", 11000.0, ""),
                new ProductSeedData("MEDIA COMPRESION DEBAJO DE RODILLA  15-20 mmHG  TALLA XL 12000", "Soportes Ortopédicos", 12000.0, ""),
                new ProductSeedData("LINNER ENCORE 24CM  6mm/ 3mm  172600", "Soportes Ortopédicos", 172600.0, ""),
                new ProductSeedData("INMOVILIZADOR DE MUÑECA LARGO AMBIDIESTRO CH", "Soportes Ortopédicos", 18128.0, ""),
                new ProductSeedData("FAJA TRASPIRABLE POSTOPERATORIA L 30000", "Soportes Ortopédicos", 33900.0, ""),
                new ProductSeedData("MEDIA COMPRESION 20-30mmHg LUXURY  TALLA M  15000", "Soportes Ortopédicos", 7500.0, ""),
                new ProductSeedData("Manga COMPRESION LYMPHGEDEMA ARM 15-20mmHg L 23000", "Soportes Ortopédicos", 23000.0, ""),
                new ProductSeedData("CODERA CON SUJECCION TALLA S 14000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("ESPALDERA POSTURAL L 16000", "Soportes Ortopédicos", 18128.0, ""),
                new ProductSeedData("INMOVILIZADOR DE PULGAR Y MUÑECA T3DE 19500", "Soportes Ortopédicos", 22093.5, ""),
                new ProductSeedData("FAJA ELASTICA 3 BANDAS XXL", "Soportes Ortopédicos", 0.0, ""),
                new ProductSeedData("MEDIA COMPRESION DEBAJO RODILLA 20-30mmHg  TALLA XXL 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MEDIA COMPRESION 20-30mmHg UNISEX COTTON TALLA M 12000", "Soportes Ortopédicos", 12000.0, ""),
                new ProductSeedData("MANGA AMES  15-20mmHg TALLA L  22000", "Soportes Ortopédicos", 22000.0, ""),
                new ProductSeedData("FAJA TRASPIRABLE POSTOPERATORIA M 30000", "Soportes Ortopédicos", 33990.0, ""),
                new ProductSeedData("CHALECO DE HOMBRO (S) DERECHO BC1082", "Soportes Ortopédicos", 36256.0, ""),
                new ProductSeedData("CHALECO DE HOMBRO (S) IZQUIERDO BC1082", "Soportes Ortopédicos", 36256.0, ""),
                new ProductSeedData("CHALECO DE HOMBRO (M) DERECHO BC1082", "Soportes Ortopédicos", 36256.0, ""),
                new ProductSeedData("CINCHA ROTULIANA  (L) BC1159", "Soportes Ortopédicos", 10197.0, ""),
                new ProductSeedData("CINCHA ROTULIANA ONE SIZE BC1109", "Soportes Ortopédicos", 11330.0, ""),
                new ProductSeedData("FAJA PARA COLOSTOMÍA DE 28 CM (M) BC1305A", "Soportes Ortopédicos", 31724.0, ""),
                new ProductSeedData("FAJA PARA COLOSTOMÍA DE 24 CM (M) BC1305", "Soportes Ortopédicos", 31724.0, ""),
                new ProductSeedData("ESTABILIZADOR ESCAPULOHUMERAL (L) BC1081", "Soportes Ortopédicos", 29458.0, ""),
                new ProductSeedData("INMOVILIZADOR CLAVICULA (M) BC1083", "Soportes Ortopédicos", 22660.0, ""),
                new ProductSeedData("INMOVILIZADOR DE CLAVICULA (S) BC1083", "Soportes Ortopédicos", 22660.0, ""),
                new ProductSeedData("MUSLERA SIMPLE BLACK LINE (L) BC1201E", "Soportes Ortopédicos", 12000.0, ""),
                new ProductSeedData("RODILLERA ABIERTA (XXL) BC1106E", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("RODILLERA ARTICULADA CORTA CON VELCRO (S) BC1105", "Soportes Ortopédicos", 33000.0, ""),
                new ProductSeedData("RODILLERA SOSTEN ROTULIANO (M) BC1102", "Soportes Ortopédicos", 10763.5, ""),
                new ProductSeedData("RODILLERA ROTULA (XL) BC1102E", "Soportes Ortopédicos", 9700.0, ""),
                new ProductSeedData("RODILLERA BALLENADA CON VELCRO (XXL) BC1104", "Soportes Ortopédicos", 18128.0, ""),
                new ProductSeedData("RODILLERA BALLENADA CON VELCRO (S) BC1104E", "Soportes Ortopédicos", 11000.0, ""),
                new ProductSeedData("RODILLERA BALLENADA CON VELCRO (M) BC1104E", "Soportes Ortopédicos", 11000.0, ""),
                new ProductSeedData("RODILLERA ROTULA CON VELCRO (XXL) BC1103E", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("FAJA HERNIA UMBILICAL (L) SUP3031BLK-L", "Soportes Ortopédicos", 22000.0, ""),
                new ProductSeedData("RODILLERA ROTULA CON VELCRO (S) BC1103E", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("RODILLERA TUBULAR (XXL) BC1101", "Soportes Ortopédicos", 10763.5, ""),
                new ProductSeedData("MEDIA COMPRESION 15-20  SHEER SUPPORT TALLA SMOLL   15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MEDIA COMPRESION LEOTARDO 20-30mmHg talla M", "Soportes Ortopédicos", 26000.0, ""),
                new ProductSeedData("INMOVILIZADOR DE MUñECA CORTO L DER", "Soportes Ortopédicos", 14500.0, ""),
                new ProductSeedData("MEDIAS PARA VARICES 20-30MMHG PUNTA CERRADA 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MEDIA PARA DIABETICOS AMES BLANCAS  S/M   10000", "Soportes Ortopédicos", 10000.0, ""),
                new ProductSeedData("HUESITO DE RODILLA PROURSA", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("MEDIA DE COMPRESION A MUSLO  20-30mmHG  22000", "Soportes Ortopédicos", 22000.0, ""),
                new ProductSeedData("FAJA TRANSPIRABLE S", "Soportes Ortopédicos", 33990.0, ""),
                new ProductSeedData("HOMBRERA DELTOIDES (M) BC1088", "Soportes Ortopédicos", 31724.0, ""),
                new ProductSeedData("CODERA SIMPLE XL 10000", "Soportes Ortopédicos", 11500.0, ""),
                new ProductSeedData("CORSE SACRO AJUSTABLE  ASPEN   30000", "Soportes Ortopédicos", 30000.0, ""),
                new ProductSeedData("RODILLERA SOSTEN ROTULIANO (XXL) BC1102", "Soportes Ortopédicos", 10763.5, ""),
                new ProductSeedData("MEDIA COMPRESION 15-20 mmHg  TALLA L sports performance Knne   15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("TOBILLERA CON AJUSTE EN 8 BLACK LINE T4 8000", "Soportes Ortopédicos", 9500.0, ""),
                new ProductSeedData("ROM ELBOW BRACE VIVE IZQUIERDA 45000", "Soportes Ortopédicos", 45000.0, ""),
                new ProductSeedData("CODERA ARTICULADA GONIOMETRA (DERECHA) SUP2069BLKR", "Soportes Ortopédicos", 45000.0, ""),
                new ProductSeedData("INMOVILIZADOR DEDO INDIVIDUAL S", "Soportes Ortopédicos", 7150.0, ""),
                new ProductSeedData("CINCHA P TENDON DE AQUILES CH 12000", "Soportes Ortopédicos", 13596.0, ""),
                new ProductSeedData("MUÑEQUERA CON DEDO LIBRE DOBLE AJUSTE", "Soportes Ortopédicos", 10000.0, ""),
                new ProductSeedData("TOBILLERA ELASTICA T2 6000", "Soportes Ortopédicos", 6798.0, ""),
                new ProductSeedData("FAJA SACRO LUMBAR CON BALLENAS T1 (solo existencias disponibles)", "Soportes Ortopédicos", 33000.0, ""),
                new ProductSeedData("MUÑEQUERA  CON DEDO LIBRE DOBLE AJUSTE", "Soportes Ortopédicos", 10000.0, ""),
                new ProductSeedData("FERULA PARA DEDO RANA  L - BLUNDING", "Soportes Ortopédicos", 5000.0, ""),
                new ProductSeedData("RODILLERA CON ORIENTADOR LATERAL S DE 20000", "Soportes Ortopédicos", 22660.0, ""),
                new ProductSeedData("CODERA CON SUJECION TALLA L 14000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("FERULA FASCITIS PLANTAR VIVE S", "Soportes Ortopédicos", 27000.0, ""),
                new ProductSeedData("SILLA FULL ORTOPÉDICA DRIVE 16 PULGADAS", "Soportes Ortopédicos", 0.0, ""),
                new ProductSeedData("FAJA SACRO LUMBAR XL", "Soportes Ortopédicos", 30800.0, ""),
                new ProductSeedData("MANGA AMES 15-20 mmHg TALLA M 23000", "Soportes Ortopédicos", 23000.0, ""),
                new ProductSeedData("MEDIA ANTIEMBOLICA COLOR BEIS  15-20mmHG  TALLA  M 11000", "Soportes Ortopédicos", 11000.0, ""),
                new ProductSeedData("MEDIA COMPRESION PANTY 20-30 mmHg  TALLA XL  15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MEDIA COMPRESION COOLMAX ANKLET 8-15mmHg  TALLA L  7500", "Soportes Ortopédicos", 7500.0, ""),
                new ProductSeedData("CODERA CON SUJECON TALLA XL 14000", "Soportes Ortopédicos", 15862.0, ""),
                new ProductSeedData("SILLA DE TRANSPORTE VIVE  100000", "Soportes Ortopédicos", 100000.0, ""),
                new ProductSeedData("MEDIA COMPRESION DEBAJO DE RODILLA 20-30mmHg TALLA M 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("KNEE SLEEVE  VERDE TALLA XXL  15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("FAJA PORTA GEL UNIVERSAL 7000", "Soportes Ortopédicos", 7931.0, ""),
                new ProductSeedData("MEDIA COMPRESION 20-30mmHg LUXURY  TALLA XL 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("FAJA SACRO LUMBAR  M", "Soportes Ortopédicos", 30800.0, ""),
                new ProductSeedData("RODILLERA FRIO - CALOR  S/m 27000", "Soportes Ortopédicos", 2700.0, ""),
                new ProductSeedData("FERULA STAXX TALLA 1", "Soportes Ortopédicos", 2500.0, ""),
                new ProductSeedData("TOBILLERA CON AJUSTE EN 8 BLACK LINE T3", "Soportes Ortopédicos", 9500.0, ""),
                new ProductSeedData("CODERA   TALLA M   8000", "Soportes Ortopédicos", 8000.0, ""),
                new ProductSeedData("MEDIA ANTIEMBOLICA BLANCA 18mmHg TALLA L 7500", "Soportes Ortopédicos", 7500.0, ""),
                new ProductSeedData("MEDIA DE COMPRESION 20-30 OPEN TOE  TALLA L 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MEDIA COMPRESION TIPO PANTY 15-20 mmHg  TALLA XL  15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MEDIA COOLMAX  OVER-THE- CALF SOCKS 20-30 mmHg - XL", "Soportes Ortopédicos", 12000.0, "COD: 111"),
                new ProductSeedData("MEDIA COMPRESION 20-30 MEDICAL SUPPORT OPEN TOE TALLA L 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("MANGA DE COMPRESION LYMPHEDEMA 20-30 mmHg AMES TALLA  SMOLL   24000", "Soportes Ortopédicos", 24000.0, ""),
                new ProductSeedData("CINCHA P TENDON DE AQUILES GR 12000", "Soportes Ortopédicos", 13596.0, ""),
                new ProductSeedData("FAJA INTERCOSTAL L 18000", "Soportes Ortopédicos", 20394.0, ""),
                new ProductSeedData("MEDIA COMPRESION TIPO PANTY 20-30 mmHg  talla XL28000", "Soportes Ortopédicos", 28000.0, ""),
                new ProductSeedData("CORSE DORSO EVERGREEN 456  AJUSTABLE 65000", "Soportes Ortopédicos", 65000.0, ""),
                new ProductSeedData("MEDIA COMPRESION MEDICAL  SUPPORT 15-20 TALLA L", "Soportes Ortopédicos", 12000.0, ""),
                new ProductSeedData("MEDIA COMPRESION 20-30 mmHg  talla M 15000", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("RODILLERA ABIERTA (M) BC1106E", "Soportes Ortopédicos", 13000.0, ""),
                new ProductSeedData("CINCHA ROTULIANA DOBLE (L) BC1160", "Soportes Ortopédicos", 15500.0, ""),
                new ProductSeedData("RODILLERA ROTULIANA (M) BC1102E", "Soportes Ortopédicos", 9700.0, ""),
                new ProductSeedData("HOMBRERA ONE SIZE 35000", "Soportes Ortopédicos", 36000.0, ""),
                new ProductSeedData("CABESTRILLO PEDIATRICO", "Soportes Ortopédicos", 8500.0, ""),
                new ProductSeedData("TOBILLERA CON SILICONA TALLA L 18000", "Soportes Ortopédicos", 18000.0, ""),
                new ProductSeedData("TOBILLERA SIMPLE BC1401E-XL", "Soportes Ortopédicos", 7931.0, ""),
                new ProductSeedData("TOBILLERA SIMPLE BC1401E-L", "Soportes Ortopédicos", 7931.0, ""),
                new ProductSeedData("TOBILLERA SIMPLE BC1401E-S", "Soportes Ortopédicos", 7931.0, ""),
                new ProductSeedData("ESPALDARA ELÁSTICO S-14500", "Soportes Ortopédicos", 15000.0, ""),
                new ProductSeedData("RODILLERA ARTICULADA SUP2072BLK", "Soportes Ortopédicos", 16000.0, ""),
                new ProductSeedData("MEDIA COMPRESION, DIABETICO 8-15 mmHg talla S", "Soportes Ortopédicos", 8900.0, ""),
                new ProductSeedData("TOBILLERA CON AJUSTE EN 8 BLACK LINE T2 8000", "Soportes Ortopédicos", 9500.0, ""),
                new ProductSeedData("MEDIA PARA DIABETICOS AMES  BLANCAS  L/XL   10000", "Soportes Ortopédicos", 10000.0, ""),
                new ProductSeedData("MEDIA COMPRESION LUXURY OPAQUE OPEN TOE KNEE  18000 TALLA M", "Soportes Ortopédicos", 18000.0, ""),
                new ProductSeedData("ESTABILIZADOR ESCAPULOHUMERAL (S) BC1081", "Soportes Ortopédicos", 29458.0, ""),
                new ProductSeedData("CHALECO DE HOMBRO (M) IZQUIERDO BC1082", "Soportes Ortopédicos", 36256.0, ""),
                new ProductSeedData("INMOVILIZADOR DE VIETNAM BC1084", "Soportes Ortopédicos", 26059.0, ""),
                new ProductSeedData("RODILLERA ABIERTA (XL) BC1106", "Soportes Ortopédicos", 16500.0, ""),
                new ProductSeedData("RODILLERA ROTULIANA (L) BC1102E", "Soportes Ortopédicos", 9700.0, ""),
                new ProductSeedData("RODILLERA BALLENADA CON VELCRO (M) BC1104", "Soportes Ortopédicos", 18128.0, "ok "),
                new ProductSeedData("COBERTOR DE YESO PARA BRAZO VIVE RHB3002CLR", "Soportes Ortopédicos", 4500.0, ""),
                new ProductSeedData("MEDIA COMPRESION UNISEX COTTON 20-30 mmHg TALLA XL 12000", "Soportes Ortopédicos", 12000.0, "")
        );

        products.forEach(item -> {
            Category category = categoryRepository.findByNameIgnoreCase(item.categoryName())
                    .orElseGet(() -> {
                        Category newCategory = new Category();
                        newCategory.setName(item.categoryName());
                        return categoryRepository.save(newCategory);
                    });

            Product product = new Product();
            product.setName(item.name());
            product.setPrice(item.price());
            product.setDescription(item.description().isBlank() ? null : item.description());
            product.setActive(true);
            product.setCategory(category);
            productRepository.save(product);
        });
    }

    private record ProductSeedData(String name, String categoryName, Double price, String description) {
    }
}